/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.text.DecimalFormat;
import javax.swing.*;
//import javax.swing.ImageIcon;
//import javax.swing.JOptionPane;
//import javax.swing.JPanel;

/**
 *
 * @author CAMI
 */
public class Quemando_Calorias extends javax.swing.JFrame {

    String option;
    /**
     * Creates new form Peso_Ideal
     */
    public Quemando_Calorias() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Actividad = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        boxActividad = new javax.swing.JComboBox<>();
        jLabel_Tiempo = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        txtPeso = new javax.swing.JTextField();
        jLabel_Peso = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel_TextKG = new javax.swing.JLabel();
        jLabel_TextCM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 213));

        jLabel_Actividad.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel_Actividad.setText("Actividad");

        jPanel2.setBackground(new java.awt.Color(255, 146, 0));

        jLabel_Titulo.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("PORCENTAJE DE GRASA CORPORAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel_Titulo)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_Titulo)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        boxActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecciona ---", "Caminar", "Tenis", "Montar en bicicleta", "Correr", "Nadar" }));
        boxActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActividadActionPerformed(evt);
            }
        });

        jLabel_Tiempo.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel_Tiempo.setText("Tiempo");

        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(255, 146, 0));
        btnCalcular.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        jLabel_Peso.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel_Peso.setText("Peso");

        btnRegresar.setBackground(new java.awt.Color(255, 146, 0));
        btnRegresar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel_TextKG.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel_TextKG.setText("kg");

        jLabel_TextCM.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel_TextCM.setText("min");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Actividad)
                    .addComponent(jLabel_Tiempo)
                    .addComponent(jLabel_Peso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(boxActividad, 0, 175, Short.MAX_VALUE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TextKG)
                    .addComponent(jLabel_TextCM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Actividad)
                    .addComponent(boxActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Tiempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Peso)
                            .addComponent(jLabel_TextKG)))
                    .addComponent(jLabel_TextCM))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        Limpiar();
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void boxActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActividadActionPerformed
        option = (String)boxActividad.getSelectedItem();
    }//GEN-LAST:event_boxActividadActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
               
        int txtTiempo1, txtPeso1;
        double resultado;
        try {
            txtTiempo1 = Integer.parseInt(txtTiempo.getText());
            double T = Double.valueOf(txtTiempo1);
            txtPeso1 = Integer.parseInt(txtPeso.getText());
            double P = Double.valueOf(txtPeso1);
            
            if(option.equals("Caminar")){
                
                resultado = ((T*2*P)/200);
                JOptionPane.showMessageDialog(this, "Usted quemó "+resultado+" Calorias","RESULTADO",JOptionPane.INFORMATION_MESSAGE);
                
            } else if(option.equals("Tenis")){
                
                resultado = ((T*5*P)/200);
                JOptionPane.showMessageDialog(this, "Usted quemó "+resultado+" Calorias","RESULTADO",JOptionPane.INFORMATION_MESSAGE);
            
            } else if(option.equals("Montar en bicicleta")){
                
                resultado = ((T*14*P)/200);
                JOptionPane.showMessageDialog(this, "Usted quemó "+resultado+" Calorias","RESULTADO",JOptionPane.INFORMATION_MESSAGE);
            
            } else if(option.equals("Correr")){
                
                resultado = ((T*6*P)/200);
                JOptionPane.showMessageDialog(this, "Usted quemó "+resultado+" Calorias","RESULTADO",JOptionPane.INFORMATION_MESSAGE);
            
            } else if(option.equals("Nadar")){
                
                resultado = ((T*9.8*P)/200);
                JOptionPane.showMessageDialog(this, "Usted quemó "+resultado+" Calorias","RESULTADO",JOptionPane.INFORMATION_MESSAGE);
            
            } else 
                JOptionPane.showMessageDialog(this, "Selecciona un género");
            
        } catch (NumberFormatException | NullPointerException e) {
            
            if (e instanceof NumberFormatException) {
                JOptionPane.showMessageDialog(this, "Ingrese solo números enteros","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            }
                JOptionPane.showMessageDialog(this, "Selecciona una Actividad","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                return;
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        Limpiar();
    }//GEN-LAST:event_txtPesoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        index I = new index();
        I.setVisible(true);
        I.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quemando_Calorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quemando_Calorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quemando_Calorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quemando_Calorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quemando_Calorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxActividad;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel_Actividad;
    private javax.swing.JLabel jLabel_Peso;
    private javax.swing.JLabel jLabel_TextCM;
    private javax.swing.JLabel jLabel_TextKG;
    private javax.swing.JLabel jLabel_Tiempo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        boxActividad.setSelectedItem("Selecciona una opción");
        txtTiempo.setText("");
    }

 
}
